language: node_js
node_js:
  - '10'
dist: trusty
sudo: required
addons:
  firefox: latest
  chrome: stable
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm run lint
script:
  - xvfb-run npm run test
  - xvfb-run npm run test:integration
deploy:
    # Live Deploy
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_BUCKET_NAME
    skip_cleanup: true
    local_dir: build/es6-bundled
    on:
      branch: master
after_deploy:
  - test $TRAVIS_BRANCH = "master" && travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $CLOUDFRONT_DISTRIBUTION_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST -o 'master'